["元数据"]
"保存为文件" = "银行流水.xlsx"
"值集[.,.]" = ["交易流水号标识", "交易时间", "金额", "付款方户名", "付款方账号", "收款方户名", "收款方账号", "摘要"]

[["合并策略"]]
"元数据"."策略名称" = "1-借贷按列区分类型表单"
"元数据"."描述" = """
  账户收支方向按照存放在不同列中的数据进行区分类型表单适用
"""
"交易时间"."数据源" = ["交易时间"]
"交易时间"."插件" = ""
"借贷方向"."数据源" = ["借贷方向"]
"借贷方向"."插件" = ""
"金额"."数据源" = ["金额"]
"金额"."插件" = "masquerade.NonSpaceEitherOne"
"付款方户名"."数据源" = ["甲户名"]
"付款方户名"."插件" = ""
"付款方账号"."数据源" = ["甲账号"]
"付款方账号"."插件" = ""
"收款方户名"."数据源" = ["乙户名"]
"收款方户名"."插件" = ""
"收款方账号"."数据源" = ["乙账号"]
"收款方账号"."插件" = ""
"摘要"."数据源" = ["摘要"]
"摘要"."插件" = ""

[["合并策略"."元数据"."完成组装"]]
"值集[.,.]" = ["交易流水号标识", "交易时间"]
"插件" = "composing.TimestampNonceFromDate"
"数据源" = ["交易时间"]
"参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"参数"."时间戳精度" = 1000
"参数"."随机数位数" = 7

[["合并策略"."元数据"."完成组装"]]
"值集[.,.]" = ["交易流水号标识", "交易时间", "金额", "付款方户名", "付款方账号", "收款方户名", "收款方账号", "摘要"]
"插件" = "composing.PermutePeersAsCreditDebit"
"数据源" = ["借贷方向", "交易流水号标识", "交易时间", "金额", "付款方户名", "付款方账号", "收款方户名", "收款方账号", "摘要"]
"参数"."收支字段" = "借贷方向"
"参数"."标识行为" = { "收" = true, "支" = false }
"参数"."交换序列" = [["收款方户名", "付款方户名"], ["收款方账号", "付款方账号"]]



[["合并策略"]]
"元数据"."策略名称" = "2-借贷按单列数值区分类型表单"
"元数据"."描述" = """
  账户收支方向按照存放在同列中的数据不同如：收入/支出
"""
"交易时间"."数据源" = ["交易时间"]
"交易时间"."插件" = ""
"借贷方向"."数据源" = ["借贷方向"]
"借贷方向"."插件" = ""
"金额"."数据源" = ["金额"]
"金额"."插件" = ""
"付款方户名"."数据源" = ["甲户名"]
"付款方户名"."插件" = ""
"付款方账号"."数据源" = ["甲账号"]
"付款方账号"."插件" = ""
"收款方户名"."数据源" = ["乙户名"]
"收款方户名"."插件" = ""
"收款方账号"."数据源" = ["乙账号"]
"收款方账号"."插件" = ""
"摘要"."数据源" = ["摘要"]
"摘要"."插件" = ""

[["合并策略"."元数据"."完成组装"]]
"值集[.,.]" = ["交易流水号标识", "交易时间"]
"插件" = "composing.TimestampNonceFromDate"
"数据源" = ["交易时间"]
"参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"参数"."时间戳精度" = 1000
"参数"."随机数位数" = 7

[["合并策略"."元数据"."完成组装"]]
"值集[.,.]" = ["交易流水号标识", "交易时间", "金额", "付款方户名", "付款方账号", "收款方户名", "收款方账号", "摘要"]
"插件" = "composing.PermutePeersAsCreditDebit"
"数据源" = ["借贷方向", "交易流水号标识", "交易时间", "金额", "付款方户名", "付款方账号", "收款方户名", "收款方账号", "摘要"]
"参数"."收支字段" = "借贷方向"
"参数"."标识行为" = { "收" = true, "支" = false }
"参数"."交换序列" = [["收款方户名", "付款方户名"], ["收款方账号", "付款方账号"]]



[["合并策略"]]
"元数据"."策略名称" = "3-借贷双方灵活排列的简易格式"
"元数据"."描述" = """
  账户收支方向按照收付关系，完整的匹配存在与付款方与收款方列中
  无须后期调整，故也不需要生成 借贷方向 列
"""
"交易时间"."数据源" = ["交易时间"]
"交易时间"."插件" = ""
"金额"."数据源" = ["金额"]
"金额"."插件" = ""
"付款方户名"."数据源" = ["甲户名"]
"付款方户名"."插件" = ""
"付款方账号"."数据源" = ["甲账号"]
"付款方账号"."插件" = ""
"收款方户名"."数据源" = ["乙户名"]
"收款方户名"."插件" = ""
"收款方账号"."数据源" = ["乙账号"]
"收款方账号"."插件" = ""
"摘要"."数据源" = ["摘要"]
"摘要"."插件" = ""

[["合并策略"."元数据"."完成组装"]]
"值集[.,.]" = ["交易流水号标识", "交易时间"]
"插件" = "composing.TimestampNonceFromDate"
"数据源" = ["交易时间"]
"参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"参数"."时间戳精度" = 1000
"参数"."随机数位数" = 7


# # ====================================


["账户五"]
"元数据"."表单名称匹配模式" = "借记卡交易明细表"
"元数据"."策略名称" = "1-借贷按列区分类型表单"
"元数据"."参数"."起始行" = 3
"元数据"."参数"."包裹行" = 0
"交易时间"."地址集[.,.]" = ["A3:B3"]
"交易时间"."插件" = "column.DateTimeFormator"
"交易时间"."参数"."输入格式" = "%Y/%m/%d %H:%M:%S"
"交易时间"."参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."非空(true/false)" = true
"借贷方向"."地址集[.,.]" = ["C3"]
"借贷方向"."插件" = "column.IdentifyByValue"
"借贷方向"."参数"."收支标值{目标键:值,...}" = {"收入" = "收", "支出" = "支"}
"金额"."地址集[.,.]" = ["D3:E3"]
"金额"."插件" = "column.ColumnHead"
"金额"."参数"."非空(true/false)" = true
"甲户名"."地址集[.,.]" = []
"甲户名"."插件" = "column.ConstantInject"
"甲户名"."参数"."值集[.,.]" = ["(test code 5)"]
"甲账号"."地址集[.,.]" = []
"甲账号"."插件" = "column.ConstantInject"
"甲账号"."参数"."值集[.,.]" = ["(test code 6)"]
"乙账号"."地址集[.,.]" = ["H3"]
"乙账号"."插件" = "column.ColumnHead"
"乙户名"."地址集[.,.]" = ["G3"]
"乙户名"."插件" = "column.ColumnHead"
"摘要"."地址集[.,.]" = ["K3"]
"摘要"."插件" = "column.ColumnHead"


["账户四"]
"元数据"."表单名称匹配模式" = ""
"元数据"."策略名称" = "1-借贷按列区分类型表单"
"元数据"."参数"."起始行" = 6
"元数据"."参数"."包裹行" = 0
"交易时间"."地址集[.,.]" = ["A6:B6"]
"交易时间"."插件" = "column.DateTimeFormator"
"交易时间"."参数"."输入格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."非空(true/false)" = true
"借贷方向"."地址集[.,.]" = ["D6:E6"]
"借贷方向"."插件" = "column.IdentifyByColumn"
"借贷方向"."参数"."收支标值{目标键:值,...}" = {"收入金额" = "收", "支出金额" = "支"}
"金额"."地址集[.,.]" = ["D6:E6"]
"金额"."插件" = "column.ColumnHead"
"金额"."参数"."非空(true/false)" = true
"甲户名"."地址集[.,.]" = ["F2"]
"甲户名"."插件" = "column.OneShot"
"甲账号"."地址集[.,.]" = ["B2"]
"甲账号"."插件" = "column.OneShot"
"乙账号"."地址集[.,.]" = ["G6"]
"乙账号"."插件" = "column.ColumnHead"
"乙户名"."地址集[.,.]" = ["H6"]
"乙户名"."插件" = "column.ColumnHead"
"摘要"."地址集[.,.]" = ["L6", "J6", "K6"]
"摘要"."插件" = "column.ColumnUnited"
"摘要"."参数"."字符串按列头格式化模式" = "{摘要} - 用途： {用途}; 附言： {附言}"


["^账户三\\W\\D{6}监管$"]
"元数据"."表单名称匹配模式" = ""
"元数据"."策略名称" = "1-借贷按列区分类型表单"
"元数据"."参数"."起始行" = 6
"元数据"."参数"."包裹行" = 0
"交易时间"."地址集[.,.]" = ["A6"]
"交易时间"."插件" = "column.DateTimeFormator"
"交易时间"."参数"."输入格式" = "%Y-%m-%d %H.%M.%S.%f"
"交易时间"."参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."非空(true/false)" = true
"借贷方向"."地址集[.,.]" = ["B6"]
"借贷方向"."插件" = "column.IdentifyByValue"
"借贷方向"."参数"."收支标值{目标键:值,...}" = {"收息" = "收", "转" = "支"}
"金额"."地址集[.,.]" = ["E6"]
"金额"."插件" = "column.ColumnHead"
"金额"."参数"."非空(true/false)" = true
"甲户名"."地址集[.,.]" = []
"甲户名"."插件" = "column.ConstantInject"
"甲户名"."参数"."值集[.,.]" = ["(test code 0)"]
"甲账号"."地址集[.,.]" = []
"甲账号"."插件" = "column.ConstantInject"
"甲账号"."参数"."值集[.,.]" = ["(test code 1)"]
"乙账号"."地址集[.,.]" = []
"乙账号"."插件" = "column.ConstantInject"
"乙账号"."参数"."值集[.,.]" = ["(test code 2)"]
"乙户名"."地址集[.,.]" = []
"乙户名"."插件" = "column.ConstantInject"
"乙户名"."参数"."值集[.,.]" = ["(test code 3)"]
"摘要"."地址集[.,.]" = ["B6"]
"摘要"."插件" = "column.ColumnHead"


["账户二"]
"元数据"."表单名称匹配模式" = "多账户查询业务处理结果"
"元数据"."策略名称" = "3-借贷双方灵活排列的简易格式"
"元数据"."参数"."起始行" = 9
"元数据"."参数"."包裹行" = 0
"交易时间"."地址集[.,.]" = ["K9:L9"]
"交易时间"."插件" = "column.DateTimeFormator"
"交易时间"."参数"."输入格式" = "%Y%m%d %H:%M:%S"
"交易时间"."参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."非空(true/false)" = true
"金额"."地址集[.,.]" = ["N9"]
"金额"."插件" = "column.ColumnHead"
"金额"."参数"."非空(true/false)" = true
"甲户名"."地址集[.,.]" = ["F9"]
"甲户名"."插件" = "column.ColumnHead"
"甲账号"."地址集[.,.]" = ["E9"]
"甲账号"."插件" = "column.ColumnHead"
"乙账号"."地址集[.,.]" = ["I9"]
"乙账号"."插件" = "column.ColumnHead"
"乙户名"."地址集[.,.]" = ["J9"]
"乙户名"."插件" = "column.ColumnHead"
"摘要"."地址集[.,.]" = ["B9", "X9:Y9"]
"摘要"."插件" = "column.ColumnUnited"
"摘要"."参数"."字符串合并连接模式" = " - "


["账户一"]
"元数据"."表单名称匹配模式" = "明细查询 "
"元数据"."策略名称" = "2-借贷按单列数值区分类型表单"
"元数据"."参数"."起始行" = 11
"元数据"."参数"."包裹行" = 0
"交易时间"."地址集[.,.]" = ["B11"]
"交易时间"."插件" = "column.DateTimeFormator"
"交易时间"."参数"."输入格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."日期格式" = "%Y-%m-%d %H:%M:%S"
"交易时间"."参数"."非空(true/false)" = true
"借贷方向"."地址集[.,.]" = ["D11"]
"借贷方向"."插件" = "column.IdentifyByValue"
"借贷方向"."参数"."收支标值{目标键:值,...}" = {"收入" = "收", "支出" = "支"}
"金额"."地址集[.,.]" = ["F11"]
"金额"."插件" = "column.ColumnHead"
"金额"."参数"."非空(true/false)" = true
"甲户名"."地址集[.,.]" = ["C5"]
"甲户名"."插件" = "column.OneShot"
"甲账号"."地址集[.,.]" = ["C4"]
"甲账号"."插件" = "column.OneShot"
"甲账号"."参数"."匹配抽取模式" = "^(\\d{16}).+$"
"乙账号"."地址集[.,.]" = ["G11"]
"乙账号"."插件" = "column.ColumnHead"
"乙户名"."地址集[.,.]" = ["H11"]
"乙户名"."插件" = "column.ColumnHead"
"摘要"."地址集[.,.]" = ["K11"]
"摘要"."插件" = "column.ColumnHead"
